steps:
  - label: "GPU julia v1.5"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "GPU julia v1.6"        # change to "v1" when 1.6 is out
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6-nightly"   # change to "1" when 1.6 is out
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "GPU julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop.jl
      - julia .ci/test.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
