steps:
  - label: "GPU julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - lib
    commands:
      - julia .ci/develop_nnlibcuda.jl
      - julia .ci/test_nnlibcuda.jl
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
  
  ## Add these when julia 1.7 is out
  # - label: "GPU julia v1"       
  #   plugins:
  #     - JuliaCI/julia#v1:
  #         version: "1"      
  #     - JuliaCI/julia-coverage#v1:
  #         codecov: true
  #         dirs:
  #           - src
  #           - lib
  #   commands:
  #     - julia .ci/develop.jl
  #     - julia .ci/test.jl
  #   agents:
  #     queue: "juliagpu"
  #     cuda: "*"
  #   timeout_in_minutes: 60

  # - label: "GPU julia nightly"
  #   plugins:
  #     - JuliaCI/julia#v1:
  #         version: "nightly"
  #     - JuliaCI/julia-coverage#v1:
  #         codecov: true
  #         dirs:
  #           - src
  #           - lib
  #   commands:
  #     - julia .ci/develop.jl
  #     - julia .ci/test.jl
  #   agents:
  #     queue: "juliagpu"
  #     cuda: "*"
  #   timeout_in_minutes: 60
