name: Documentation

on:
  push:
    branches:
      - master
      - staging
      - trying
    tags: '*'
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  docs:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          # minimum supported Julia version (keep in sync with Project.toml [compat])
          version: '1.10'
      - uses: julia-actions/cache@v3
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      # `docs/make.jl` runs `makedocs(doctest=true)`, so this also checks the doctests.
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
